### ISSUE TITLE
Unable to load AWS Credentials 

### ISSUE THREAD

**Issue by kali251648** [Flangvik/TeamFiltration#10]
While running ./create_fireprox_instances.sh in kali. I am getting below error:

Unable to load AWS credentials
[+] Created  that points to https://login.microsoftonline.com/
Unable to load AWS credentials
[+] Created  that points to https://login.microsoftonline.us/
Unable to load AWS credentials
[+] Created  that points to https://teams.microsoft.com/api/mt/
Unable to load AWS credentials
[+] Created  that points to https://autologon.microsoftazuread-sso.com/
Unable to load AWS credentials

I am using free AWS tier and have added both access key and security key in the file.

**Comment by Flangvik** [comment]
This is an issue related to FireProx and/or you setup of AWS access key. See this https://github.com/ustayready/fireprox/issues/17
