### ISSUE TITLE
SSL error in enumeration module

### ISSUE THREAD

**Issue by def-q** [Flangvik/TeamFiltration#13]
Hello,
I'm trying to test TeamFiltration, everything goes fine until I choose the email format. Then I have an SSL connection issue (see the screen shot below). I'm clearly not sure where this is coming from, I tried different test domain but the same error is showing up.

Any clues on what could be the cause ? 

Thank you ! :)

![image](https://user-images.githubusercontent.com/112073425/192269080-27b1e3ad-c96e-47f3-b542-abdf02c0a22c.png)

**Comment by def-q** [comment]
Here is the requests when using the --debug flag:

![image](https://user-images.githubusercontent.com/112073425/192278643-0563f6f3-201d-4a59-8b18-27c560d66151.png)

**Comment by kluo84** [comment]
I have the same issue 
ENUM] 10/8/2022 10:43:52 PM EST SOFT ERROR ENUM  => The SSL connection could not be established, see inner exception.

**Comment by trevor-jones-AWN** [comment]
Same issue here.

**Comment by Flangvik** [comment]
This is either related to the fireprox URL in the config not working / invalid. To easily debug this, fire up Burp on port 8080 and use '--debug' with Teamfiltration. That way you can actually inspect the requests.

**Comment by jsarkisian** [comment]
Same issue here, just adding moral support.

**Comment by scaery** [comment]
Use the windows version. It failed on OSX and Linux versions for me as well with the same exact error message. So tested the same config on a Windows VM and suddenly all worked like intended.

**Comment by Flangvik** [comment]
For now please use a Windows machine / VM when running into this issue, best guess is that's it related to how the cross-platform-compile handles SSL/TLS libs for the different operating systems.

**Comment by queencitycyber** [comment]
Had this same issue. Your `openssl.conf` file is probably borked:

```
sed -i 's/openssl_conf = openssl_init/#openssl_conf = openssl_init/g' /etc/ssl/openssl.cnf
```
