### ISSUE TITLE
Teams not module not starting up

### ISSUE THREAD

**Issue by wiebewillems** [Flangvik/TeamFiltration#14]
As an example, I configured a personal (free) Microsoft account that can login to Teams. I specified those in the config.json as sacrificial username & password. I don't get output from the --validate-teams option - also not that the sacrificial account is not valid. Does the Microsoft account need to meet certain conditions to be used with the API?

![image](https://user-images.githubusercontent.com/35848547/198566038-f5162a27-8fe8-4c78-ade9-1849ccf4aa36.png)

**Comment by Flangvik** [comment]
Hi, needs to be an AAD joined account, cannot be a private / personal account

**Comment by wiebewillems** [comment]
Good to know, thanks for the quick reply!
