### ISSUE TITLE
TeamFiltration 3.5.0 and source build on Win10: Invalid URI: The URI is empty.

### ISSUE THREAD

**Issue by ad0nis** [Flangvik/TeamFiltration#22]
.\TeamFiltration.exe --config C:\Path\To\TeamFiltration\MyConfig.json --outpath C:\Path\To\Output\test\ --enum --domain mytargetdomain.tld --validate-msol

  ╓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╖
 ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬┤                              ╟╬╬╜╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬╡                              │      ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬╡                              ││      ╙╬╬╜╘ └╙╜╬╬╬╬╬╬
╬╬╬╬╡         ╓╥╥╬╬╬╬╬╬╥╥╖         ││       │        ╬╬╬╬╬
╬╬╬╬╡     ╓╬╫╬╜╜┘      ╙╜╜╬╫╬┐     ││       ││       └╬╬╬╬
╬╬╬╬┤    ╬╬╜╙╩╬╖╓          ╙╬╬╬    ││       ││        ╬╬╬╬
╬╬╬╬┤   ╬╜      ╙╬╫╖╖ ╓      ╙╬╖   ││      ├││        ╬╬╬╬
╬╬╬╬┤  ╬╬     ╓╖   ╙╬╬╬╬╬╬╦    ╬╬  │┌    ╓╬┤││       ╓╬╬╬╬
╬╬╬╬┤ ╓╬┤     ╬╬╬   ╬╬╬╬╬╬╬╬╜╜╜╬╬╖ ╟╬╬╬╬╬╬╬╬╬╕      ┌╬╬╬╬╬
╬╬╬╬┤ ╬╬┤     ╙╩┘   ╙╬╬╬╬╬╩    ╟╬╬ ╙╜╜╜╜╜╜╜╜╜╬╬╖╖╖╦╬╬╬╬╬╬╬
╬╬╬╬┤ ╬╬┤                      ╟╬╬ ││         ╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬┤  ╬╬   ╦╖            ╗╖   ╬╬  ││         │       ╬╬╬╬
╬╬╬╬┤  └╬┐   ╙╬╖╖      ╓╬╬╜   ╓╬┘  ││         │       ╬╬╬╬
╬╬╬╬┤   └╬╖    ╙╩╨╬╬╬╩╨╜╜   ╒╬╬    ││         │       ╬╬╬╬
╬╬╬╬┤    ╙╬╬╬╖           ┌╖╫╬╜┘    ││         │       ╬╬╬╬
╬╬╬╬┤       ╙╩╬╬╬╥╥╥╥╥╥╫╬╬╜╜       ││         │       ╬╬╬╬
╬╬╬╬┤            ╙╙╜╜╜╛            ││         │       ╬╬╬╬
╬╬╬╬┤                              ││         │    ╓╖╬╬╬╬╬
╬╬╬╬┤                              ││         ╬╦╦╬╬╬╬╬╬╬╬╬
╬╬╬╬┤                              ││     ╓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬┤                              ╬╬╬╖╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
 └╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╜
   ╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜

[♥] TeamFiltration V3.5.0 PUBLIC, created by @Flangvik at @TrustedSec
[+] Args parsed --config C:\Path\To\TeamFiltration\MyConfig.json --outpath C:\Path\To\Output\test\ --enum --domain mytargetdomain.tld --validate-msol
[+] AWS SecretKey and AccessKey found, FireProx endpoint will be automagically created for each spray-rotation
    |=> [1] john.smith@mytargetdomain.tld
    |=> [2] john@mytargetdomain.tld
    |=> [3] johnjs@mytargetdomain.tld
    |=> [4] johns@mytargetdomain.tld
    |=> [5] johnsmith@mytargetdomain.tld
    |=> [6] jsmith@mytargetdomain.tld
    |=> [7] smith@mytargetdomain.tld
    |=> [8] smithj@mytargetdomain.tld
    |=> [9] john_smith@mytargetdomain.tld

[?] Select an email format #> 6
[ENUM] 2/14/2023 5:27:54 PM EST Filtering out previusly attempted accounts
[ENUM] 2/14/2023 5:27:54 PM EST Warning, this method may give some false positive accounts
[ENUM] 2/14/2023 5:27:54 PM EST Enumerating 48705 possible accounts, this will take ~41 minutes
[FIREPROX] 2/14/2023 5:27:57 PM EST Created endpoint https://[REDACTED].execute-api.eu-west-3.amazonaws.com/fireprox/
[ENUM] 2/14/2023 5:27:57 PM EST SOFT ERROR ENUM  => Invalid URI: The URI is empty.

**Comment by ad0nis** [comment]
Just to add to this, I was able to open the endpoint it had created in AWS and ended up on a Microsoft login page, so it seemed to be functioning to me.

**Comment by ad0nis** [comment]
Sorry - didn't mean to close.

**Comment by Flangvik** [comment]
This is a issue with the --validate-msol method, use --validate-teams or --validate-login if possible. There is another issue https://github.com/Flangvik/TeamFiltration/issues/25 finding --validate-msol is pretty much broken currently due to MS changes.
