### ISSUE TITLE
Precompiled binary does not run on latest Ubuntu Server 22.10

### ISSUE THREAD

**Issue by okazymyrov** [Flangvik/TeamFiltration#23]
ubuntu@ip-10-0-0-24:/tmp$ uname -a
Linux ip-10-0-0-24 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-10-0-0-24:/tmp$ ./TeamFiltration  --outpath ./out --config ./TeamFiltrationConfig_Example.json --enum --validate-msol --domain example.com

  ╓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╖
 ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬┤                              ╟╬╬╜╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬╡                              │      ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬╡                              ││      ╙╬╬╜╘ └╙╜╬╬╬╬╬╬
╬╬╬╬╡         ╓╥╥╬╬╬╬╬╬╥╥╖         ││       │        ╬╬╬╬╬
╬╬╬╬╡     ╓╬╫╬╜╜┘      ╙╜╜╬╫╬┐     ││       ││       └╬╬╬╬
╬╬╬╬┤    ╬╬╜╙╩╬╖╓          ╙╬╬╬    ││       ││        ╬╬╬╬
╬╬╬╬┤   ╬╜      ╙╬╫╖╖ ╓      ╙╬╖   ││      ├││        ╬╬╬╬
╬╬╬╬┤  ╬╬     ╓╖   ╙╬╬╬╬╬╬╦    ╬╬  │┌    ╓╬┤││       ╓╬╬╬╬
╬╬╬╬┤ ╓╬┤     ╬╬╬   ╬╬╬╬╬╬╬╬╜╜╜╬╬╖ ╟╬╬╬╬╬╬╬╬╬╕      ┌╬╬╬╬╬
╬╬╬╬┤ ╬╬┤     ╙╩┘   ╙╬╬╬╬╬╩    ╟╬╬ ╙╜╜╜╜╜╜╜╜╜╬╬╖╖╖╦╬╬╬╬╬╬╬
╬╬╬╬┤ ╬╬┤                      ╟╬╬ ││         ╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬┤  ╬╬   ╦╖            ╗╖   ╬╬  ││         │       ╬╬╬╬
╬╬╬╬┤  └╬┐   ╙╬╖╖      ╓╬╬╜   ╓╬┘  ││         │       ╬╬╬╬
╬╬╬╬┤   └╬╖    ╙╩╨╬╬╬╩╨╜╜   ╒╬╬    ││         │       ╬╬╬╬
╬╬╬╬┤    ╙╬╬╬╖           ┌╖╫╬╜┘    ││         │       ╬╬╬╬
╬╬╬╬┤       ╙╩╬╬╬╥╥╥╥╥╥╫╬╬╜╜       ││         │       ╬╬╬╬
╬╬╬╬┤            ╙╙╜╜╜╛            ││         │       ╬╬╬╬
╬╬╬╬┤                              ││         │    ╓╖╬╬╬╬╬
╬╬╬╬┤                              ││         ╬╦╦╬╬╬╬╬╬╬╬╬
╬╬╬╬┤                              ││     ╓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬┤                              ╬╬╬╖╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬
 └╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╜
   ╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜╜

[♥] TeamFiltration V3.5.0 PUBLIC, created by @Flangvik at @TrustedSec
[+] Args parsed --outpath ./out --config ./TeamFiltrationConfig_Example.json --enum --validate-msol --domain example.com
No usable version of libssl was found
Aborted (core dumped)

**Comment by okazymyrov** [comment]
I have also tested on latest Kali and Windows Server Windows_Server 2022. Different issues, but the same result. On Windows the exfil module worked, but not enum. I think docker would be the best option.

**Comment by Flangvik** [comment]
Looking at https://github.com/dotnet/core/issues/4749 

```
If this is .NET Core 3.1, then no. There's no solution. .NET Core 3.1 just doesn't support OpenSSL 3.x, so you really do need to have an older version of OpenSSL (either 1.0 or 1.1) for it to work.

On the other hand, .NET Core 3.1 goes EOL next month. The newer supported releases - 6.0 and 7.0 - both support OpenSSL 3.0. Maybe you can think about moving to one of those supported releases 1 month early?
```

Does seem like i need to update from .NET Core 3.1 "finally"

**Comment by Flangvik** [comment]
Looking at https://github.com/dotnet/core/issues/4749 

```
If this is .NET Core 3.1, then no. There's no solution. .NET Core 3.1 just doesn't support OpenSSL 3.x, so you really do need to have an older version of OpenSSL (either 1.0 or 1.1) for it to work.

On the other hand, .NET Core 3.1 goes EOL next month. The newer supported releases - 6.0 and 7.0 - both support OpenSSL 3.0. Maybe you can think about moving to one of those supported releases 1 month early?
```

Does seem like i need to update from .NET Core 3.1 "finally"

**Comment by okazymyrov** [comment]
M... I do not think so... 

```sh
...
libssl3/jammy-updates,jammy-security,now 3.0.2-0ubuntu1.8 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries
...
aspnetcore-runtime-6.0/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  ASP dotNET Core runtime

dotnet-apphost-pack-6.0/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  Internal - targeting pack for Microsoft.NETCore.App 6.0

dotnet-host/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  dotNET host command line

dotnet-hostfxr-6.0/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  dotNET host resolver

dotnet-runtime-6.0/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  dotNET runtime

dotnet-sdk-6.0/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  dotNET 6.0 Software Development Kit

dotnet-sdk-6.0-source-built-artifacts/jammy-updates,jammy-security 6.0.113-0ubuntu1~22.04.1 amd64
  Internal package for building dotNet 6.0 Software Development Kit

dotnet-targeting-pack-6.0/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  Internal - targeting pack for Microsoft.NETCore.App 6.0

dotnet-templates-6.0/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed,automatic]
  dotNET 6.0 templates

dotnet6/jammy-updates,jammy-security,now 6.0.113-0ubuntu1~22.04.1 amd64 [installed]
  dotNET CLI tools and runtime
```

And the output from ```dotnet --info```
```sh
p# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.113
 Commit:    4a23b50f97

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.113/

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017

.NET SDKs installed:
  6.0.113 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by okazymyrov** [comment]
What Linux distribution was it tested on? I could docker it ;)

**Comment by Flangvik** [comment]
The pre compiled binaries needs to be re-compiled for net 5.0, not just the end system having the runtime
