### ISSUE TITLE
Stack trace when running without specifying config json in command line

### ISSUE THREAD

**Issue by dirkjanm** [Flangvik/TeamFiltration#24]
According to the docs, the config will be loaded from the current directory if not specified. This however throws a stack trace with the config being null.

Changing the following line from `else if` to `if` seems to correct this by allowing the file to be loaded if it's not specified but does exist:

https://github.com/Flangvik/TeamFiltration/blob/61554dfcdff0b34c1fac64ae490ee1a85baea3b2/TeamFiltration/TeamFiltration/Handlers/GlobalArgumentsHandler.cs#L51

**Comment by Flangvik** [comment]
I swear i fixed this a long time back , eitherway thanks. Working on a bigger update atm so i'll add this to it

**Comment by Flangvik** [comment]
Fix
