### ISSUE TITLE
Error validating MSOL enum method

### ISSUE THREAD

**Issue by tuxnam** [Flangvik/TeamFiltration#25]
In the --validate-msol method, you check the following, to see if GetCredentialType is supported or not:

if (!string.IsNullOrEmpty(postRespObject.EstsProperties?.CallMetadata?.HisRegion))

However, CallMetadata and HisRegion are not (anymore at least) part of the EstsProperties key from my research.
It will rather give you two main properties: UserTenantBranding and DomainType.
This is based on the triplet DomainType, ThrottleStatus and IfExistsResult that you will be able to see if you can enumerate accounts or not.
Your current way of checking will give "not supported" for probably all tenants today, while it is supported for part of them.

**Comment by Flangvik** [comment]
Thanks for the input, as you point out, seems MS has been making changes since this was implemented. i'll make sure this get fixed near future (i'm currently working on a massive update so trying to avoid maing to many changes to the current online repo)
