### ISSUE TITLE
Email Format Support

### ISSUE THREAD

**Issue by devnull044** [Flangvik/TeamFiltration#26]
Currently the only available formats offered appear to be:
```
    |=> [1] john.smith@domain.com
    |=> [2] john@domain.com
    |=> [3] johnjs@domain.com
    |=> [4] johns@domain.com
    |=> [5] johnsmith@domain.com
    |=> [6] jsmith@domain.com
    |=> [7] smith@domain.com
    |=> [8] smithj@domain.com
    |=> [9] john_smith@domain.com
```
Would love to see and option to specify an email format or add more formats to the list. Had a engagement where the format was `j.smith@domain.com`

**Comment by Flangvik** [comment]
Should be pretty doable to either add more formats or add support for dynamic formats
