### ISSUE TITLE
What are the SDK pre-requsites?

### ISSUE THREAD

**Issue by sp00ks-git** [Flangvik/TeamFiltration#33]
trying to build and recieving this error:
Severity	Code	        Description	
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0.	

I have SDK versions 6 + 7 insalled.

dotnet --list-sdks
5.0.411 [C:\Program Files\dotnet\sdk]
6.0.400 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]

**Comment by Flangvik** [comment]
You need to specify the project TeamFiltration.csproj when compiling from the source. The binaries uploaded are compiled on NET7.0

**Comment by sp00ks-git** [comment]
Yes I was using the csproj file to open the project.
I found the issue, it was the version (15) of Visual Studio 2022 I was using. Updating to the latest (17) solved the issue.
