### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sp00ks-git** [Flangvik/TeamFiltration#34]
Hi apologies if this is obvious, when I try using the following on a known domain :

TeamFiltration.exe --config C:\data\TeamFiltration\TeamFiltrationConfig_Example.json --outpath C:\data\TeamFiltration\TeamFiltration\outpath --enum --domain DOMAIN.COM --validate-login

I get:

SOFT ERROR ENUM  => Object reference not set to an instance of an object.

Am i missing somthing? It's my understanding that i dont have to specify a microsoft account if using the --validate-login option right?

Looking to achieve grabbing and validating legit email address from a tennant from a non joined domain machine.

**Comment by Flangvik** [comment]
Hi, what does your config look like? (sensor secrets ofc)
