### ISSUE TITLE
Email exists but the database does not get populated

### ISSUE THREAD

**Issue by thehackerish** [Flangvik/TeamFiltration#36]
I am using the Teams technique in TeamFiltration. Using the Debug option, I see that some emails return a valid TenantId and that the email is valid and found in many attributes in the JSON response. However, the UserPrincipalName does not match the username, but the `givenName` matches the email. 

Here is an example for the username `d.bauer@redacted.com`. I anonymized all the data.

```
[{"tenantId":"REDACTED","isShortProfile":false,"accountEnabled":true,"featureSettings":{"coExistenceMode":"TeamsOnly"},"userPrincipalName":"d19@redacted.com","givenName":"d.bauer@redacted.com","surname":"","email":"d19@redacted.com","tenantName":"REDACTED","displayName":"Dave Bauer","type":"Federated","mri":"8:orgid:REDACTED","objectId":"REDACTED"}]
```

I was wondering why do you check that the UserPrincipalName should be equal to the email in this line: https://github.com/Flangvik/TeamFiltration/blob/e125f79a566ab9e7c0d3f4845fac48bc4af9f58c/TeamFiltration/TeamFiltration/Handlers/TeamsHandler.cs#L199

**Comment by Flangvik** [comment]
This is a good find 👍👍Just what I wanted when releasing this so more people (it being used against more clients, thus seeing more tenant configs and edge cases). Thinkings the best approach would be to merge those into an `or` statement, comparing both the `givenName` and `userPrincipalName` properties to the username.

**Comment by thehackerish** [comment]
Perfect! I will add a pull request considering what I have in my tests. The approach would be to look for the email in all attributes of the objects in the list returned and store it if it matches any.

**Comment by AntonyBwana** [comment]
In my case I was using the MSOL module. I realised that the emails that have been verified aren't being stored.

**Comment by sadpotatos123** [comment]
> In my case I was using the MSOL module. I realised that the emails that have been verified aren't being stored.

I had the same problem when using  --validate-msol.

**Comment by Flangvik** [comment]
Should be fixed in https://github.com/Flangvik/TeamFiltration/releases/tag/v3.5.3
