### ISSUE TITLE
how to import emails

### ISSUE THREAD

**Issue by sadpotatos123** [Flangvik/TeamFiltration#39]
I am very confused how to import emails when I use spray ,there are only --passwords parameters, not --usernames.   Do I need to modify the database directly to import the email list?

**Comment by sadpotatos123** [comment]
I don't want to verify  emails again, and sometimes using "--enum --usernames email.list" won't save emails

**Comment by sadpotatos123** [comment]
#36

**Comment by Flangvik** [comment]
Check the YouTube videos on this, might help clear things up :) 
https://www.youtube.com/watch?v=oo2isrbfYmg
https://www.youtube.com/watch?v=YyuxEuzQa9k
