### ISSUE TITLE
SOFT ERROR ENUM

### ISSUE THREAD

**Issue by mstump2s** [Flangvik/TeamFiltration#41]
Hi, im trying to test the TeamFiltration.exe, but unfortunately I'm not able to start it properly. 
I get the following Error for all validation methods:

TeamFiltration.exe --outpath C:\Clients\Example\TFOutput --config TeamFiltrationConfig_Example.json --enum --validate-login --domain censored.onmicrosoft.com

[ENUM] 11.08.2023 09:20:39 EST Filtering out previusly attempted accounts
[ENUM] 11.08.2023 09:20:40 EST Warning, THIS METHOD WILL PRODUCE LOGIN ATTEMPTS AND IF USED FREQUENTLY,MAY LOCKOUT ACCOUNTS!
[ENUM] 11.08.2023 09:20:40 EST Enumerating 248231 accounts with password Welcome@2023!, this will take ~41 minutes
[ENUM] 11.08.2023 09:20:40 EST SOFT ERROR ENUM  => Object reference not set to an instance of an object.

The Config File looks like this: 
{
    "pushoverAppKey": "", 
    "pushoverUserKey": "", 
	"dehashedEmail" : "",
	"dehashedApiKey": "", 
    "sacrificialO365Username": "censored@censored.onmicrosoft.com", 
    "sacrificialO365Passwords": "censored",  
    "proxyEndpoint": "http://127.0.0.1:8080",
    "AWSAccessKey": "",
    "AWSSecretKey": "",
	"UserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Teams/1.3.00.30866 Chrome/80.0.3987.165 Electron/8.5.1 Safari/537.36",
    "AwsRegions":["us-east-1", "us-west-1", "us-west-2", "ca-central-1", "eu-central-1", "eu-west-1", "eu-west-2", "eu-west-3", "eu-north-1"]
  }
Do you have any idea what the problem could be?
Thanks in advance!

**Comment by Flangvik** [comment]
You are missing the AWSAccessKey and AWSSecretKey from the config, https://youtu.be/J8ohuanP2gA
