### ISSUE TITLE
 SOFT ERROR ENUM  => Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Christopher-Vaughan-MSSA** [Flangvik/TeamFiltration#42]
Good afternoon, 

I am receiving  SOFT ERROR ENUM  => Object reference not set to an instance of an object error when attempting to --validate-teams. 

I ran the command - .\TeamFiltration.exe --outpath .\MyOutputDir --config .\myConfig.json --enum --validate-teams --domain mydomain.com

<img width="757" alt="image" src="https://github.com/Flangvik/TeamFiltration/assets/102161245/c44321d0-6abe-4ecf-b201-3dc09bbe6ec0">

My config file: 

<img width="855" alt="image" src="https://github.com/Flangvik/TeamFiltration/assets/102161245/2fb196f3-c3bd-4689-99ce-64be1e131595">

**Comment by Flangvik** [comment]
You are missing the AWSAccessKey and AWSSecretKey from the config, see this video for a full config / setup guide https://youtu.be/J8ohuanP2gA :)
