### ISSUE TITLE
JWT is not well formed

### ISSUE THREAD

**Issue by Christopher-Vaughan-MSSA** [Flangvik/TeamFiltration#43]
Flangvik- 

Issue when attempting to exfil after successfully spray.  I am getting an IDX12709 error that the JWT is not well formed. 

<img width="953" alt="image" src="https://github.com/Flangvik/TeamFiltration/assets/102161245/0ea5d3c4-d4a3-4a56-a9ce-90420fb8a351">

Any advice? 

Thanks!

**Comment by Flangvik** [comment]
Interestingly, this error seems to indicate that the token received in the response of the valid login is not a valid JWT token, which is really weird. Are there any more details you could give without disclosing anything sensitive? Any special SSO or other setup for this client?

**Comment by Christopher-Vaughan-MSSA** [comment]
The target user is a regular user with federated authentication. The client is hybrid joined. Happy to share screen captures or anything else that may help figure it out.
