### ISSUE TITLE
--aad-sso broken

### ISSUE THREAD

**Issue by SadStrategy** [Flangvik/TeamFiltration#45]
Hi!

If I use the "--spray --aad-sso" options, I keep getting the response of "AADSTS81016", even though the password I entered is correct. The database marks the attempt as "Valid=false".

However, when I omit the "--aad-sso" parameter, everything works as expected, and I get the response "VALID, MUST ENROLL MFA."
![aad-sso](https://github.com/Flangvik/TeamFiltration/assets/144791816/870a0471-f0aa-49a4-83ea-f9616fa27168)
![working](https://github.com/Flangvik/TeamFiltration/assets/144791816/61c83e3e-b8b7-4e87-a56d-bfb5b0070cb9)

**Comment by Flangvik** [comment]
Looking at this -> https://guillaumeben.xyz/Microsoft-365-enumeration/

This indidcates that the tenant does not not use Seamless SSO (see [SecureWorks article](https://www.secureworks.com/research/undetected-azure-active-directory-brute-force-attacks), and more details here on [Seamless SSO](https://learn.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso)).
