### ISSUE TITLE
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by HSIS007** [Flangvik/TeamFiltration#47]
Any idea what is this error about ?

I am running it from Windows 10 pro machine

[+] Args parsed --outpath .\Out\ --config .\Config.json --spray --domain test.com --usernames .\Valid_Emails.txt --seasons-only
[SPRAY]  EST Sleeping between 60-100 minutes for each round
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at TeamFiltration.Modules.Spray.SprayAsync(String[] args)
   at TeamFiltration.Program.Main(String[] args)
   at TeamFiltration.Program.<Main>(String[] args)

**Comment by Flangvik** [comment]
Take  a look at the getting started YouTube video and make sure your config it setup correctly https://youtu.be/J8ohuanP2gA

**Comment by PocketDC** [comment]
Having the same issue here, config file is set up appropriately as far as I can tell
![image](https://github.com/Flangvik/TeamFiltration/assets/29924527/e471a00d-c295-4c3d-b4cc-80dcc5f1f310)
