### ISSUE TITLE
Only one usage of each socket address

### ISSUE THREAD

**Issue by Fr0gZero** [Flangvik/TeamFiltration#49]
First of all thanks for the development in this tool so far this has been awesome! 

Below is an error I have seen occur at the same spot of reserved usernames from the statistically likely enum method. 

[+] Args parsed --config config.json --outpath C:\Users\null\OneDrive\Desktop\Pentests\null\external --enum --domain null --validate-login

"({myamazonid}.execute-api.us-west-2.amazonaws.com:443)) (Only one usage of each socket address (protocol/network address/port) is normally permitted."

The above error is outputted to the console. 

Also to note if I re-run the enumeration for 30 minutes or so nothing is outputted and the number of potential enumerateable accounts stays the same.

**Comment by Flangvik** [comment]
I'm closing this, if this is still an ongoing issue, please let me know.
