### ISSUE TITLE
Unhandled exception. System.NullReferenceException

### ISSUE THREAD

**Issue by PocketDC** [Flangvik/TeamFiltration#50]
Having the same issue here, config file is set up appropriately as far as I can tell
![image](https://github.com/Flangvik/TeamFiltration/assets/29924527/e471a00d-c295-4c3d-b4cc-80dcc5f1f310)

_Originally posted by @PocketDC in https://github.com/Flangvik/TeamFiltration/issues/47#issuecomment-1912463227_

**Comment by PocketDC** [comment]
Nevermind, figured it out.

It won't accept a "usernames" argument in spraying. You need to enumerate first even if you know the usernames are valid. So I presume because there were no usernames in the database it was getting the null reference problem.

Might suggest a clarification in the --spray documentation that the usernames need to exist in the databse, OR accept a file as username inputs

**Comment by barrett092** [comment]
This helped me
