### ISSUE TITLE
Skip Fireprox for e.g. Exfiltration

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [Flangvik/TeamFiltration#7]
Hey,

More a feature request than an issue.

In some situations it might not be needed to go over FireProx, e.g. if you already have valid creds (so no Smart Lockout Anyway) and just want to use the exfiltration module. It would be nice from my point of view to also have a switch for not using FireProx in those cases.

In the moment it will just crash when not having a proper FireProx config.

Greetings

**Comment by Flangvik** [comment]
Yup, i agree with this. I think the FireProx integration should be updated in such a way that's in completely optional. For both enum,spraying and exfiltration 👍 I'll start looking into it

**Comment by rdrzaz** [comment]
I have valid creds on a test tenant (sacrificial usernames and passwords). Do I need the API keys in the config file? Can they be left blank? Also, can I leave the foxproxs urls blank? I would just want to use the --exfil module (for now) to show specific people that use O365 they really need a conditional access policy set yesterday with MFA enforced. I have heard every excuse why MFA is a burden until I have to do IR on compromised accounts. Anyways, does your --exfil work without the config? If not will it work without the foxprox urls and API keys? Thank you for your help.

**Comment by Flangvik** [comment]
This has now been resolved with 3.3.8. The exfil module will no longer require a configuration "at all" in order to exfiltrate data from an given account.

**Comment by S3cur3Th1sSh1t** [comment]
Nice, thanks! 👌

**Comment by fsacer** [comment]
As a note, it still writes a message if you don't provide the config file, but it goes through without it which was a bit confusing.
